easy_admin:
    entities:
      #- App\Entity\User
      #- App\Entity\Fight
      #- App\Entity\Alien
      User:
        class: App\Entity\User
        form:
          fields:
            - { property: 'name', type: 'text', label: 'Name' }
            - { property: 'surname', type: 'text', label: 'Surname' }
            - { property: 'mail', type: 'email', label: 'Mail' }
            - { property: 'password', type: 'text', label: 'Password' }
            - { property: 'pseudo', type: 'text', label: 'Pseudo' }
            - { property: 'birthdate', type: 'App\Form\MyCustomDate', label: 'Birthdate' }
            - { property: 'nb_credit', type: 'number', label: 'Number of SpaceCoin' }
            - { property: 'win', label: 'win', value: '0' }
            - { property: 'defeat', label: 'defeat', value: '0' }
            - { property: 'pending_fight', type: 'checkbox', value: false }
            - { property: 'rating', label: 'Rating', value: '0' }
            - { property: 'img_user', type: 'file', label: User Image } #<- c'est un peux la merde la --'
      Alien:
        class: App\Entity\Alien
      Fight:
        class: App\Entity\Fight


