easy_admin:
    entities:
      #- App\Entity\User
      #- App\Entity\Fight
      #- App\Entity\Alien
      User:
        class: App\Entity\User
        list:
          fields:
            - "id"
            - "name"
            - "surname"
            - "mail"
            - "password"
            - "pseudo"
            - "birthdate"
            - "nb_credit"
            - "win"
            - "defeat"
            - "pending_fight"
            - "rating"
            - "img_user"
            - "roles"
        form:
          fields:
            - { property: 'name', type: 'text', label: 'Name' }
            - { property: 'surname', type: 'text', label: 'Surname' }
            - { property: 'mail', type: 'email', label: 'Mail' }
            - { property: 'plainPassword', type: 'text', label: 'Plain password' }
            - { property: 'password', type: 'text', label: 'Password' }
            - { property: 'pseudo', type: 'text', label: 'Pseudo' }
            - { property: 'birthdate', type: 'App\Form\MyCustomDate', label: 'Birthdate' }
            - { property: 'nb_credit', type: 'number', label: 'Number of SpaceCoin' }
            - { property: 'win', label: 'win', value: '0' }
            - { property: 'defeat', label: 'defeat', value: '0' }
            - { property: 'pending_fight', type: 'checkbox', value: false }
            - { property: 'rating', label: 'Rating', value: '0' }
            - { property: 'img_user', type: 'file', label: User Image }
      Alien:
        class: App\Entity\Alien
      Fight:
        class: App\Entity\Fight
        form:
          fields:
           - { property: 'user1'}
           - { property: 'user2'}
           - { property: 'alien1'}
           - { property: 'alien2'}
           - { property: 'bet'}
           - { property: 'odd_fighter1'}
           - { property: 'odd_fighter2'}
           - { property: 'date', type: 'App\Form\MyCustomDate', label: 'date' }
           - { property: 'accepted'}
      Bet:
        class: App\Entity\Bet

